name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - development
      - main
  push:
    branches:
      - main   # Only deploy on main pushes

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests (Vitest)
        run: npm run test -- --run

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      FLASK_ENV: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install backend dependencies
        run: pipenv install --dev --deploy --ignore-pipfile

      - name: Run backend tests
        run: pipenv run pytest

  deploy-frontend:
    needs: [frontend, backend]   # Only deploy if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d32qtbbuibrs73a3tap0
          api-key: ${{ secrets.RENDER_API_TOKEN }}

  deploy-backend:
    needs: [frontend, backend]   # Only deploy if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Backend to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d32qqkidbo4c73amkccg
          api-key: ${{ secrets.RENDER_API_TOKEN }}
